FROM ubuntu:22.04

#MAINTAINER Ivan Font <ifont@redhat.com>
MAINTAINER Lacoste <git@delfosse.com>

# Update and install packages
# Mongo
RUN curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
#RUN echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
# Install Packages
RUN apt-get -y update && apt-get -y install mongodb-org

# node.js
RUN apt-get update && sudo apt-get install -y ca-certificates curl gnupg
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN sudo apt-get update && sudo apt-get install -y nodejs

#RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
#    apt-get install -y nodejs

# Add mongod data directory
RUN mkdir -p /data/db

# Create app directory and specify volume that will be bind mounted at runtime
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
VOLUME ["/usr/src/app"]

# expose mongo port
EXPOSE 27017

# Expose port 8080
EXPOSE 8080

# Run mongo
CMD /usr/bin/mongod --fork --replSet rs0 && npm run dev
